### ISSUE TITLE
WinError 10013

### ISSUE THREAD

**Issue by BeemerDream** [GSTDiandre/ps2-discord-rpc#10]
Hi!

When I start the py program it gives me this error.

Thanks in advance

**Comment by GSTDiandre** [comment]
Sounds like a privilege level issue, I'd verify whether UAC/antivirus isn't interfering with the software.

**Comment by BeemerDream** [comment]
Thanks, I'll have a look on that.

**Comment by BeemerDream** [comment]
I disabled the UAC and gave permission in windows firewall to py.exe on incoming and outgoing  but I still get the error. I´ll provide a screenshot 
![Screenshot 2024-09-28 16_11_12](https://github.com/user-attachments/assets/92389860-d15f-4888-b37b-ac67c4b3ba86)
I read that it has to be with software using the same port. Is that in your software or is it in Python? Should be Python I think. I'll try change the port and we'll see

**Comment by BeemerDream** [comment]
It wasn't the port either. Python are using ports 8054-8059, and nothing else are using these ports.

**Comment by GSTDiandre** [comment]
The software simply requests a free port from the OS by binding to port 0:

`    s = socket.socket(socket.AF_INET, socket.SOCK_RAW, socket.IPPROTO_IP)`
`    s.bind((HOST_IP, 0))`

On my machine, it gets assigned a very high port number, close to 65535:

![image](https://github.com/user-attachments/assets/4c549d72-4127-4dcb-9d54-b01b3d56fe6b)

You might have an issue with port assignments on yours? Admin rights, UAC, firewall, antivirus, that sort of stuff. I'd test in a VM or on another system just to be sure.

**Comment by BeemerDream** [comment]
I uninstalled Python and reinstalled it and did the pip install requirements.txt file. But now when I try to run your software it just flashes in the window and closes immediately.

**Comment by GSTDiandre** [comment]
> I uninstalled Python and reinstalled it and did the pip install requirements.txt file. But now when I try to run your software it just flashes in the window and closes immediately.

Have the dependencies been installed properly? What happens when you run `python ps2rpc.py` from command line?

**Comment by BeemerDream** [comment]
Do you mean the three in the text file? In that case yes. I'll try to run it thru command line.

**Comment by BeemerDream** [comment]
> > I uninstalled Python and reinstalled it and did the pip install requirements.txt file. But now when I try to run your software it just flashes in the window and closes immediately.
> 
> Have the dependencies been installed properly? What happens when you run `python ps2rpc.py` from command line?

Well, what do you know? It worked now. Thank you so much.
