### ISSUE TITLE
Now, he detects opl but not the game

### ISSUE THREAD

**Issue by JoaoManoelSilvaMorais** [GSTDiandre/ps2-discord-rpc#8]
Just as I mentioned, in Discord it shows that I am idle, but when I open a game, it doesn't update my status.
Here is the link to the log file: [logs.log](https://github.com/GSTDiandre/ps2-discord-rpc/files/11716501/logs.log)

The game I tested is Grand Theft Auto: San Andreas (SLUS-209.46).
I have installed a translation mod for the game, which translates it from English to Brazilian Portuguese. The mod is available on MixMods website: [SA Tradução Português para GTA SA PC, Android, PS2 (2021)](https://www.mixmods.com.br/2022/03/sa-traducao-portugues-para-gta-sa-pc-android-ps22021/)

**Comment by GSTDiandre** [comment]
What is the full path of the game you're trying to access?

The script expects your games to be stored in the ``DVD`` folder at the root of the SMB share, and the filename needs to adhere to OPL's naming standard, which is ``SLUS_123.45.GAMENAME.iso``

As an example, if your share is ``C:\PS2SMB``, the full path of the ISO should be ``C:\PS2SMB\DVD\SLUS_209.46.Grand Theft Auto San Andreas.iso``

As long as the game is in the proper folder and its name starts with the game code in this format, it should be properly detected regardless of what the full name is/what the ISO contents are (as in, whether the game is patched or not).

Also, make sure you're using OPL v.1.1.0.

**Comment by JoaoManoelSilvaMorais** [comment]
I tested it with OPL 1.1.0 and changed the naming of the .iso files.

The path to my DVD folder is E:\PS2\PS2\DVD
![image](https://github.com/GSTDiandre/ps2-discord-rpc/assets/85969033/df67fe16-7714-4f6c-a1ed-ea72a1a89103)

I don't think I need to send the same log since it had the same result.

The game I tested this time was Gran Turismo 4 (SCUS-973.28).
Its naming: SCUS_973.28.Gran Turismo 4.iso

**Comment by GSTDiandre** [comment]
I've tested the script with the same path and it works fine; Make sure that you're sharing ``E:\PS2\PS2`` instead of ``E:\PS2\`` in OPL server, since the DVD folder needs to be at the root of the share.

If it still doesn't work, it would mean the net filter isn't correctly filtering information from the network. I'll add some debugging code to the next release so I can take a look at what your PS2 is accessing through the logs file.

**Comment by JoaoManoelSilvaMorais** [comment]
Yes, it is.
![image](https://github.com/GSTDiandre/ps2-discord-rpc/assets/85969033/f6525b92-bbd5-40b2-b151-c6405d5b25a8)

I will try a different path to see if it works. I will test with E:\ps2smb and I will let you know the results.

**Comment by JoaoManoelSilvaMorais** [comment]
It seems that I can't change the sharing folder for the OPL Server :P. I'll have to stick with `E:\PS2\PS2` for now.

**Comment by GSTDiandre** [comment]
The network request that asks your SMB server to open the game ISO contains the path relative to the share root. As long as it starts with ``\DVD\``, the rest of the path should not matter.

If you know how to capture packets with Wireshark, you can send me a pcap file containing the network traffic from your PS2's IP when you're launching a game and I'll take a look at it to see if it's a filter mismatch. If not, I'll get another release ready that logs the packets to ``logs.log`` so we can solve the issue.

**Comment by JoaoManoelSilvaMorais** [comment]
Yeah, give me a time. I need to install Wireshark.

**Comment by JoaoManoelSilvaMorais** [comment]
Here it is.
https://drive.google.com/file/d/1PBIiJb1TmDtc6H0Fy93HBjfatDWXDhgU/view?usp=sharing
Let me know your email so that I can grant you access. I'm not sure if it's safe to have this file exposed here.

**Comment by GSTDiandre** [comment]
Requested access

**Comment by JoaoManoelSilvaMorais** [comment]
It's done.

**Comment by GSTDiandre** [comment]
Your packets are identical to mine and so is the game name offset, so it's making me think the script is reading packets that are truncated differently than on my machine.

I've gone ahead and got rid of the offset-based packet slicing entirely, the script should now search the whole packet for a valid game path. Try [this ``ps2rpc.py`` instead](https://github.com/GSTDiandre/ps2-discord-rpc/files/11740461/ps2rpc.zip) and send me your ``log.logs`` file. I'll push an update if this works.

**Comment by JoaoManoelSilvaMorais** [comment]
Hey man, I'm going to try the script tomorrow, it's already late here in my country.

**Comment by PatoPatola** [comment]
Hey man, I'm going to try the script tomorrow, it's already late here in my country.

**Comment by JoaoManoelSilvaMorais** [comment]
> Your packets are identical to mine and so is the game name offset, so it's making me think the script is reading packets that are truncated differently than on my machine.
> 
> I've gone ahead and got rid of the offset-based packet slicing entirely, the script should now search the whole packet for a valid game path. Try [this `ps2rpc.py` instead](https://github.com/GSTDiandre/ps2-discord-rpc/files/11740461/ps2rpc.zip) and send me your `log.logs` file. I'll push an update if this works.

```
Traceback (most recent call last):
  File "C:\Users\joaom\Downloads\Compressed\ps2-discord-rpc-v.0.3-beta\ps2rpc.py", line 6, in <module>
    import ping3
ModuleNotFoundError: No module named 'ping3'
```

No `logs.log` generated.

**Comment by GSTDiandre** [comment]
Run ``pip install ping3`` in command line. I believe you haven't been using the latest release, the requirements are now in ``requirements.txt``.

EDIT: nevermind, I forgot to make v4 visible. It's now up. If you download it, use it with the script I linked.

**Comment by JoaoManoelSilvaMorais** [comment]
[logs.log](https://github.com/GSTDiandre/ps2-discord-rpc/files/11748193/logs.log)
More logs, tested with Gta and Gran Turismo.

**Comment by GSTDiandre** [comment]
There should be debug-level messages in that log, are you using the script as I linked it [here](https://github.com/GSTDiandre/ps2-discord-rpc/files/11740461/ps2rpc.zip)? It's different from the v4 release.

Example of what you should be seeing:

![image](https://github.com/GSTDiandre/ps2-discord-rpc/assets/17102726/ee81096c-3fe7-486e-8e3a-dd63b9e18b09)


I also see your IP address has changed to ``192.168.1.103`` when it was ``192.168.1.104`` in the capture, are you still using the local IP of your ethernet interface?

Also, are both your devices connected to a local network through a router, or is the PS2 connected directly with a crossover cable?

**Comment by JoaoManoelSilvaMorais** [comment]
[logs.log](https://github.com/GSTDiandre/ps2-discord-rpc/files/11748859/logs.log)

Here you go, now with the ps2rpc linked here. 

I am using a different IP address because my internet connection has gone down for some reason.

Edit: I tested with Gran Turismo 4, there was no response on Discord, it just said that OPL was idle. And my computer is connected with ps2 through a router.

**Comment by GSTDiandre** [comment]
Seems to me like there's something preventing the script from reading your network packets, or at least from getting the correct data from them. Double check you're running the command prompt as admin. I'll modify the script so it dumps the PS2's packets in ``logs.log`` in debug mode.

**Comment by JoaoManoelSilvaMorais** [comment]
> Seems to me like there's something preventing the script from reading your network packets, or at least from getting the correct data from them. Double check you're running the command prompt as admin. I'll modify the script so it dumps the PS2's packets in the logs.log in debug mode.

Do you think the router is causing this issue? I'm facing a problem where my internet service provider doesn't grant me permission to modify the router settings. As a result, I'm unable to play PS2 games online because, for some unknown reason, the router is blocking the ports required for my PS2.

**Comment by GSTDiandre** [comment]
My guess is probably not. Your computer is reading the correct packets from your console and is processing SMB correctly as well, but the script is either not parsing the same data as your OS (and Wireshark) or it's not detecting the data it's looking for. As for PS2 ports, you might need to forward some ports for online play if your ISP blocks them, and that's going to be tough with no access to your router. It still shouldn't affect SMB or this script in most cases.

I've tested this script on multiple machines, I've never had any issues with reading packets before.

Give [this version](https://github.com/GSTDiandre/ps2-discord-rpc/files/11749112/ps2rpc.zip) a quick run, I'm curious to see what it generates.

**Comment by JoaoManoelSilvaMorais** [comment]
[logs.log](https://github.com/GSTDiandre/ps2-discord-rpc/files/11749459/logs.log)
Here you go

**Comment by GSTDiandre** [comment]
The only packet the script reads coming from the PS2 is the initial NETBios name request, that's packet #2 from your pcap file. That packet is sent to 255.255.255.255, which means it's received by every device in your network and isn't destined to any specific IP.

Either you've specified the wrong host IP address, or some other software (firewall/antivirus and the like) is preventing the script from accessing packets tagged for your machine in that socket.

**Comment by JoaoManoelSilvaMorais** [comment]
The host IP is the ipv4 provided by ipconfig in cmd isn't it? I will test without the firewall.

**Comment by GSTDiandre** [comment]
The host IP should match the IP you're using in OPL's settings page to connect to your SMB share. To be sure, run ``ipconfig /all`` in command line to display a list of your network interfaces and their associated IPs.

**Comment by JoaoManoelSilvaMorais** [comment]
> The host IP is the ipv4 provided by ipconfig in cmd isn't it? I will test without the firewall.

It worked! It seems that the firewall was blocking everything. I'll check if I can add Python as an exception in the firewall rules so that I don't have to disable it for the script to work. Anyway, thank you and sorry for the inconvenience.

**Comment by GSTDiandre** [comment]
Great! I'll increment the release and disable the debugging features. You can download the newer release so that the script stops printing all your PS2 network activity in ``logs.log``, because that won't be pretty.

If you can, test the script with whatever games you have and let me know if there are any detection issues or game cover/name display anomalies.

**Comment by PatoPatola** [comment]
> Great! I'll increment the release and disable the debugging features. You can download the newer release so that the script stops printing all your PS2 network activity in `logs.log`, because that won't be pretty.
> 
> If you can, test the script with whatever games you have and let me know if there are any detection issues or game cover/name display anomalies.

Sure, I will test different games whenever I have time.

**Comment by JoaoManoelSilvaMorais** [comment]
> > Great! I'll increment the release and disable the debugging features. You can download the newer release so that the script stops printing all your PS2 network activity in `logs.log`, because that won't be pretty.
> > If you can, test the script with whatever games you have and let me know if there are any detection issues or game cover/name display anomalies.
> 
> Sure, I will test different games whenever I have time.
