### ISSUE TITLE
Elevated command prompt

### ISSUE THREAD

**Issue by BeemerDream** [GSTDiandre/ps2-discord-rpc#9]
Hi!

I dont understand how to do this:

Open an elevated command prompt in the same directory, then run pip install -r requirements.txt

Am I at the right place?

![Screenshot 2024-09-22 22_20_40](https://github.com/user-attachments/assets/962ac395-eb4d-4252-afa3-661125c745d2)

**Comment by BeemerDream** [comment]
Solved it

**Comment by GSTDiandre** [comment]
@BeemerDream Would appreciate if you let me know if rich presence works, I'm planning to rewrite this project for general use to avoid needing to install Python manually.

**Comment by BeemerDream** [comment]
The pip command worked, but I got the problem with WinError 10013, that I believe is that it's using the same port as something else is using. I'll try change the port.
